[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi", "py3", "pyw", "ptl", ".pythonstartup", ".pythonrc", "SConstruct"]
shebangs = ["python"]
roots = ["setup.py", "setup.cfg", "pyproject.toml"]
comment-token = "#"
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {} 
formatter = { command = "black", args = ["-"] }
auto-format = true

[[language]]
auto-format = true
name = "markdown"

[language.formatter]
args = ["--prose-wrap=always", "--stdin", "--parser=markdown"]
command = "prettier"
